// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package event

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	CreatedAt            string   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_c8ff6f7ba3cb6210, []int{0}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (dst *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(dst, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Event) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type ListRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Keyword              string   `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_c8ff6f7ba3cb6210, []int{1}
}
func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (dst *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(dst, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ListRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

type ListResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Events               []*Event `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_c8ff6f7ba3cb6210, []int{2}
}
func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (dst *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(dst, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ListResponse) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type StoreRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	CreatedAt            string   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreRequest) Reset()         { *m = StoreRequest{} }
func (m *StoreRequest) String() string { return proto.CompactTextString(m) }
func (*StoreRequest) ProtoMessage()    {}
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_c8ff6f7ba3cb6210, []int{3}
}
func (m *StoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreRequest.Unmarshal(m, b)
}
func (m *StoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreRequest.Marshal(b, m, deterministic)
}
func (dst *StoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreRequest.Merge(dst, src)
}
func (m *StoreRequest) XXX_Size() int {
	return xxx_messageInfo_StoreRequest.Size(m)
}
func (m *StoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StoreRequest proto.InternalMessageInfo

func (m *StoreRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *StoreRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *StoreRequest) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type StoreResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool     `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreResponse) Reset()         { *m = StoreResponse{} }
func (m *StoreResponse) String() string { return proto.CompactTextString(m) }
func (*StoreResponse) ProtoMessage()    {}
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_c8ff6f7ba3cb6210, []int{4}
}
func (m *StoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreResponse.Unmarshal(m, b)
}
func (m *StoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreResponse.Marshal(b, m, deterministic)
}
func (dst *StoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreResponse.Merge(dst, src)
}
func (m *StoreResponse) XXX_Size() int {
	return xxx_messageInfo_StoreResponse.Size(m)
}
func (m *StoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StoreResponse proto.InternalMessageInfo

func (m *StoreResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *StoreResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StoreResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*Event)(nil), "event.Event")
	proto.RegisterType((*ListRequest)(nil), "event.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "event.ListResponse")
	proto.RegisterType((*StoreRequest)(nil), "event.StoreRequest")
	proto.RegisterType((*StoreResponse)(nil), "event.StoreResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EventCommandClient is the client API for EventCommand service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventCommandClient interface {
	Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error)
}

type eventCommandClient struct {
	cc *grpc.ClientConn
}

func NewEventCommandClient(cc *grpc.ClientConn) EventCommandClient {
	return &eventCommandClient{cc}
}

func (c *eventCommandClient) Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error) {
	out := new(StoreResponse)
	err := c.cc.Invoke(ctx, "/event.EventCommand/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventCommandServer is the server API for EventCommand service.
type EventCommandServer interface {
	Store(context.Context, *StoreRequest) (*StoreResponse, error)
}

func RegisterEventCommandServer(s *grpc.Server, srv EventCommandServer) {
	s.RegisterService(&_EventCommand_serviceDesc, srv)
}

func _EventCommand_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventCommandServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventCommand/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventCommandServer).Store(ctx, req.(*StoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventCommand_serviceDesc = grpc.ServiceDesc{
	ServiceName: "event.EventCommand",
	HandlerType: (*EventCommandServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _EventCommand_Store_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event.proto",
}

// EventQueryClient is the client API for EventQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventQueryClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
}

type eventQueryClient struct {
	cc *grpc.ClientConn
}

func NewEventQueryClient(cc *grpc.ClientConn) EventQueryClient {
	return &eventQueryClient{cc}
}

func (c *eventQueryClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/event.EventQuery/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventQueryServer is the server API for EventQuery service.
type EventQueryServer interface {
	List(context.Context, *ListRequest) (*ListResponse, error)
}

func RegisterEventQueryServer(s *grpc.Server, srv EventQueryServer) {
	s.RegisterService(&_EventQuery_serviceDesc, srv)
}

func _EventQuery_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventQueryServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventQuery/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventQueryServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventQuery_serviceDesc = grpc.ServiceDesc{
	ServiceName: "event.EventQuery",
	HandlerType: (*EventQueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _EventQuery_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event.proto",
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_event_c8ff6f7ba3cb6210) }

var fileDescriptor_event_c8ff6f7ba3cb6210 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcf, 0x4e, 0xc2, 0x40,
	0x10, 0xc6, 0x43, 0xf9, 0x27, 0xd3, 0x4a, 0x74, 0xe0, 0xd0, 0x10, 0x4d, 0x48, 0xe3, 0x81, 0x78,
	0xa0, 0x11, 0x4f, 0x7a, 0x53, 0xa3, 0x31, 0xea, 0x41, 0xcb, 0xc5, 0x9b, 0x59, 0xe8, 0x84, 0x34,
	0xca, 0x6e, 0xed, 0x2e, 0x18, 0xae, 0xbe, 0x82, 0x8f, 0xe6, 0x2b, 0xf8, 0x20, 0xa6, 0xd3, 0x45,
	0x21, 0x91, 0x8b, 0xb7, 0x9d, 0x6f, 0x67, 0x7e, 0xfd, 0xbe, 0xe9, 0x82, 0x4b, 0x73, 0x92, 0xa6,
	0x9f, 0x66, 0xca, 0x28, 0xac, 0x72, 0xd1, 0xd9, 0x9b, 0x28, 0x35, 0x79, 0xa1, 0x50, 0xa4, 0x49,
	0x28, 0xa4, 0x54, 0x46, 0x98, 0x44, 0x49, 0x5d, 0x34, 0x05, 0x37, 0x50, 0xbd, 0xcc, 0xdb, 0xb0,
	0x09, 0x4e, 0x12, 0xfb, 0xa5, 0x6e, 0xa9, 0xd7, 0x88, 0x9c, 0x24, 0x46, 0x84, 0xca, 0x48, 0xc5,
	0x0b, 0xdf, 0x61, 0x85, 0xcf, 0xb8, 0x0f, 0x30, 0xce, 0x48, 0x18, 0x8a, 0x9f, 0x84, 0xf1, 0xcb,
	0x7c, 0xd3, 0xb0, 0xca, 0x99, 0x09, 0x4e, 0xc0, 0xbd, 0x4b, 0xb4, 0x89, 0xe8, 0x75, 0x46, 0xda,
	0xe0, 0x0e, 0x94, 0x45, 0x9a, 0x58, 0x64, 0x7e, 0x44, 0x1f, 0xea, 0xcf, 0xb4, 0x78, 0x53, 0x59,
	0x6c, 0xb1, 0xcb, 0x32, 0xb8, 0x02, 0xaf, 0x18, 0xd5, 0xa9, 0x92, 0x9a, 0xfe, 0x98, 0x3d, 0x80,
	0x1a, 0xe7, 0xd1, 0xbe, 0xd3, 0x2d, 0xf7, 0xdc, 0x81, 0xd7, 0x2f, 0xb2, 0xb2, 0xfb, 0xc8, 0xde,
	0x05, 0x43, 0xf0, 0x86, 0x46, 0x65, 0xb4, 0xd9, 0xc3, 0x3f, 0x72, 0xdd, 0xc2, 0xb6, 0x85, 0x6e,
	0x74, 0x57, 0x6c, 0xcf, 0xf9, 0xd9, 0x9e, 0x0f, 0x75, 0x3d, 0x1b, 0x8f, 0x49, 0x6b, 0xc6, 0x6d,
	0x45, 0xcb, 0x72, 0xf0, 0x08, 0x1e, 0x5b, 0xbe, 0x50, 0xd3, 0xa9, 0x90, 0x31, 0x5e, 0x43, 0x95,
	0xe1, 0xd8, 0xb2, 0x81, 0x56, 0xfd, 0x77, 0xda, 0xeb, 0x62, 0xf1, 0xfd, 0xa0, 0xfd, 0xfe, 0xf9,
	0xf5, 0xe1, 0x34, 0x83, 0x46, 0x38, 0x3f, 0x0a, 0xb9, 0xe1, 0xb4, 0x74, 0x38, 0xb8, 0x07, 0x60,
	0xf2, 0xc3, 0x8c, 0xb2, 0x05, 0x9e, 0x43, 0x25, 0xdf, 0x28, 0xa2, 0x25, 0xac, 0xfc, 0x99, 0x4e,
	0x6b, 0x4d, 0xb3, 0xd0, 0x5d, 0x86, 0xba, 0xf8, 0x0b, 0x1d, 0xd5, 0xf8, 0x8d, 0x1c, 0x7f, 0x07,
	0x00, 0x00, 0xff, 0xff, 0x23, 0x06, 0x21, 0x7b, 0x57, 0x02, 0x00, 0x00,
}
